version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: vulnerable_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      DB_NAME: vulnerable_bank
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
