name: DevSecOps Security Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Secret Scanning dengan Gitleaks
    - name: Secret Scanning
      uses: gitleaks/gitleaks-action@v2
    
    # SCA Scan dengan Trivy
    - name: SCA Scan Dependencies
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    # SAST Scan dengan Semgrep
    - name: SAST Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/security-audit
    
    # Upload Security Reports
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: *.sarif
        retention-days: 30
    
    # Critical Vulnerability Check
    - name: Check for Critical Vulnerabilities
      id: check-critical
      run: |
        echo "has_critical=true" >> $GITHUB_OUTPUT
        echo "🚨 Simulation: Critical vulnerabilities found!"
