name: DevSecOps Security Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    name: Security Scanning
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Secret Scanning with Gitleaks
      uses: gitleaks/gitleaks-action@v2
    
    - name: SCA Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: SAST Scan with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/security-audit
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: *.sarif
        retention-days: 30
    
    - name: Check Results
      run: |
        echo "✅ Security scanning completed!"
        echo "📊 Reports available in Artifacts"
